name: Vulnerability Report

description: Report some vulnerability that can be exploited.

labels: bug

body:
  - type: textarea
    attributes:
      label: Possible exploiting method
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solutions
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
