name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add dependencies
      run: |
        sudo apt update 
        sudo apt install libjsoncpp-dev 
    - name: build
      run: ./tools/build.sh
